apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: mysql
type: Opaque
data:
  mysql-root-password: MTIzNDU2  # "123456" en base64
  mysql-database: Y3Jvbm9qb2Jz  # "cronojobs" en base64
  mysql-user: YWRtaW4=          # "admin" en base64
  mysql-password: YWRtaW4=      # "admin" en base64
